#pragma once

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LT, DIR_RT, DIR_END };

enum OBJID{OBJ_PLAYER, OBJ_MONSTER, OBJ_PATTACK, OBJ_MATTACK, OBJ_INVEN, OBJ_ITEM, OBJ_MOUSE, OBJ_UI, OBJ_BUTTONS,OBJ_END };

enum STAGEID{STAGE_LOGO, STAGE_LOBBY, STAGE_1, STAGE_2, STAGE_3, STAGE_4,STAGE_END};