#pragma once

//enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LT, DIR_RT, DIR_END };

enum OBJID{OBJ_PLAYER, OBJ_PATTACK, OBJ_MONSTER, OBJ_MATTACK,  OBJ_ITEM, OBJ_BLOCK, OBJ_SHOP,OBJ_EFFECT, OBJ_UI, OBJ_INVEN, OBJ_BUTTONS,OBJ_QUICKSLOT, OBJ_ICON, OBJ_MOUSE, OBJ_END };

enum STAGEID{STAGE_LOGO, STAGE_LOBBY, STAGE_1, STAGE_2, STAGE_3, STAGE_4,STAGE_END};

enum LINEID {LEFT, RIGHT, END};

enum PORTALID { PORTAL1, PORTAL2, PORTAL3, ROFE,PORTAL_END };

enum SKILLID {NORMAL, PSKILL1, PSKILL2, PSKILL3, PSKILL4, PSKILL_END};

enum ITEMID {MONEY, WEAPON, GLOVE, WEAR, HP, MP, ITEM_END};

enum BUTTONID {LOBBY_BUTTON, SKILL_BUTTON1, SKILL_BUTTON2, SKILL_BUTTON3, SKILL_BUTTON4, BUTTON_END};
